Let's try to run tests on every commit in a branch (during build).

diff --git a/bin/test-ci-build b/bin/test-ci-build
--- a/bin/test-ci-build
+++ b/bin/test-ci-build
@@ -1,12 +1,21 @@
 #!/usr/bin/env sh
 
 npm run dev-setup &&
+npm run compile &&
 npm run lint &&
 npm run test-cov &&
-npm run lint-cov || exit 1
+npm run lint-cov &&
+npm run test-ci-build-all-commits
+
+status=$?
+
+if [ "$status" -gt 0 ]; then
+  echo "test-ci tasks returned $status. failing build!";
+  exit 1;
+fi
 
 # https://circleci.com/docs/environment-variables
-if [ -n "$CI" ]; then
+if [ -n "$CI" ] && [ "$CIRCLE_BRANCH" = "master" ]; then
   echo "sending lcov data to coveralls.io"
   cat coverage/lcov.info | coveralls
   echo "sending lcov data to codeclimate"
